apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden
  namespace: bitwarden
  labels:
    app: bitwarden
data:
  SMTP_HOST: "email-smtp.eu-west-1.amazonaws.com"
  SMTP_FROM: "example@example.tld"
  SMTP_PORT: "587"
  SMTP_SSL: "true"
  # nginx-ingress-controller has built in support for Websockets
  # Project: https://github.com/kubernetes/ingress-nginx
  WEBSOCKET_ENABLED: "true"
  DATA_FOLDER: "/data"
  DOMAIN: "https://bitwarden.example.tld"
  ROCKET_WORKERS: "5"
  SHOW_PASSWORD_HINT: "false"
  WEB_VAULT_ENABLED: "true"
  ROCKET_PORT: "8080"

  # Bitwarden RS settings
  SIGNUPS_ALLOWED: "false"
  LOG_FILE: "/data/bitwarden.log"
