kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bitwarden-claim
  namespace: bitwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 25G
